# Numpy Tricks

In [24]:
#np.sort :-returns a sortedcopy of array

import numpy as np
a = np.random.randint(1,100,15)
print(a)
print(np.sort(a))
print()

b = np.random.randint(1,100,24).reshape(6,4)
print(b)
print()
print(np.sort(b)) #YE matrix ko row wise sort karega
print()
#cloumn wise ke liye axis=0 kardo
print(np.sort(b,axis=0))
print()

# descending order main sort karne liye:-
np.sort(a)[::-1] #for linear array

#@D arrays ko column wise and row wise descendinng sort karne ke  liye hum 2d numpy slicing ka use karenge

print()
print (np.sort(b,axis=1)[:,::-1]) #ab hoga kya ?? np.sort ek row wise sorted matrix return karega jispe hum slicing kar rahe hain

#ab slicing main comma ke pehle jitni rows chahiye woh batate hai to saari rioows dedo.Comma ke baad humne column bhi saare mange lekin negative indexing ke saath matlab ulte column dega yni ki jo humare column hai wo descending hoo jayege jisse column ke end ke sabse bade elements jo hai woh start main chale jayenge or hume row wise decending matrix mil jayega 


print()

#column wise descending order matrix
print(np.sort(b,axis=0)[::-1,:])


[35 36 78 27 70 98  2  3 30 45 91 12 52 20 81]
[ 2  3 12 20 27 30 35 36 45 52 70 78 81 91 98]

[[40 79 79 72]
 [69 64 93 97]
 [92 73  9 76]
 [67 61 93 63]
 [64 12 31  7]
 [35  9  1 36]]

[[40 72 79 79]
 [64 69 93 97]
 [ 9 73 76 92]
 [61 63 67 93]
 [ 7 12 31 64]
 [ 1  9 35 36]]

[[35  9  1  7]
 [40 12  9 36]
 [64 61 31 63]
 [67 64 79 72]
 [69 73 93 76]
 [92 79 93 97]]


[[79 79 72 40]
 [97 93 69 64]
 [92 76 73  9]
 [93 67 63 61]
 [64 31 12  7]
 [36 35  9  1]]

[[92 79 93 97]
 [69 73 93 76]
 [67 64 79 72]
 [64 61 31 63]
 [40 12  9 36]
 [35  9  1  7]]


In [17]:
#np.append()  #values ko normally append karega aat the arrays end but for 2D matrix it appends values along the mentioned axis at array's end(simple shabdon main jo axis doge us axis ke end main append kar dega )

print(np.append(a,200))
print()
#Ab main chahta hoon b ke end main ek column aajye jo pure 1 ka column ho 
print(np.append(b,np.ones((b.shape[0],1)),axis=1))
print(np.append(b,np.ones((1,b.shape[1])),axis=0))


[  2   2  99   2  46  10  38  33  99  89  81  52  34  40  87 200]

[[78. 40. 14. 81.  1.]
 [14. 18.  6. 10.  1.]
 [ 2.  6. 71. 40.  1.]
 [82. 45. 47.  6.  1.]
 [40. 55. 16. 97.  1.]
 [33. 40. 99. 10.  1.]]
[[78. 40. 14. 81.]
 [14. 18.  6. 10.]
 [ 2.  6. 71. 40.]
 [82. 45. 47.  6.]
 [40. 55. 16. 97.]
 [33. 40. 99. 10.]
 [ 1.  1.  1.  1.]]


In [18]:
# np.concatenate whi kaam karta hai jo stacking karta hai like agar axis=1 doge to ye horizontal stacking karega bas rows same honi chahiye dono matrices ki 

#axis=0 is like vertical stacking isme column same hone chahiye 

# code
c = np.arange(6).reshape(2,3)
d = np.arange(12).reshape(4,3)
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
d = np.arange(12).reshape(4,3)
c = np.arange(24).reshape(4,6)
np.concatenate((c,d),axis=1)


array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2],
       [ 6,  7,  8,  9, 10, 11,  3,  4,  5],
       [12, 13, 14, 15, 16, 17,  6,  7,  8],
       [18, 19, 20, 21, 22, 23,  9, 10, 11]])

In [ ]:
# np.unique:- we can get unique values from an array.array ko as argument denge 

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e) #sare unique items ko array main daalke dedega 


array([1, 2, 3, 4, 5, 6])

In [23]:
# np.expans_dims:with its help hum ek array ke dimension ko expand kar skte hai
print(np.expand_dims(a,axis=0)) #row ke along expansion
print(np.expand_dims(a,axis=1)) #column ke along expansion  
a.shape

[[ 2  2 99  2 46 10 38 33 99 89 81 52 34 40 87]]
[[ 2]
 [ 2]
 [99]
 [ 2]
 [46]
 [10]
 [38]
 [33]
 [99]
 [89]
 [81]
 [52]
 [34]
 [40]
 [87]]


(15,)

In [ ]:
# np.where function returns the indices of elements in an input where the given condition is satisfied 

#Suppose wo saare elements ka index  chahiye jo 50 se bade hai
a[np.where(a>50)] #fancy indexing bhi lagadi 

#Ab 50 se zyada walo  ko 0 se replace kardo replacement ke liye use 
np.where(a>50,0,a) #format is like np.where(condition,true hua to isse replace kardo ,false hua to isse ya kuch mat karo )




array([2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0])

In [ ]:
#np.argmax function returns inndices of the max element of the array
print(np.argmax(a))
print()
print(b)
print()
#2D array main 
print(f"Indexes of max elements of all rows are:{np.argmax(b,axis=1)}")  #isme axis default 1 hi rahegi  and ye saare rows ke max element ke indexes ko array main daalke return karega 

print(f"Indexes of max elements of all columns are:{np.argmax(b,axis=0)}") #saare columns ke max element ke indeexes ko array main daalke return karega 
 #argmin works the same but min elements ka index dega 


5

[[40 79 79 72]
 [69 64 93 97]
 [92 73  9 76]
 [67 61 93 63]
 [64 12 31  7]
 [35  9  1 36]]

Indexes of max elements of all rows are:[1 3 0 2 0 3]
Indexes of max elements of all columns are:[2 0 1 1]


In [ ]:
# numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

#For bette understanding virat kohli ne 7 match khele and usne har matchmain kuch follwing runs banaye:-
#1->25,2->18,3->59,4->61,5->0,6->52,7->100

#ab suppose  har match ke baad uske career runs nikalne hai to aise nikalenge :-
#1->25
# 2->25=18
# 3->25+18+59
# 4->25+18+59+61
# 5->25+18+59+61+0
# 6->25+18+59+61+0+52
# 7->25+18+59+61+0+52+100=312 (career runs of virat kohli )=cumulative sum 

In [ ]:
print(a)
np.cumsum(a) #output check kar lena smajh jaoge 

np.cumsum(b) #we know b is a 2D array to ye b ko  1D main convert karega and then us 1d ka cumulative sum nikalke array return karega 
print(b)
np.cumsum(b,axis=0) #column wise cumsum 
np.cumsum(b,axis=1)#row wise cumsum


[35 36 78 27 70 98  2  3 30 45 91 12 52 20 81]
[[40 79 79 72]
 [69 64 93 97]
 [92 73  9 76]
 [67 61 93 63]
 [64 12 31  7]
 [35  9  1 36]]


array([[ 40,  79,  79,  72],
       [109, 143, 172, 169],
       [201, 216, 181, 245],
       [268, 277, 274, 308],
       [332, 289, 305, 315],
       [367, 298, 306, 351]])

In [ ]:
#cumprod for  cumulative product same bhai 

In [ ]:
#np.percentile used to compute the nth percentile of the given data along the specified axis 

np.percentile(a,100)
#100 percentile chahiye 
#100 percentile is max(sabse aage)0 is min(sabse peeche) 58 is median (middle )(adhe aage and adhe pecche )

In [ ]:
#np.histogram() ek given range main frequency count batata hai 

# `np.histogram()` — Complete Guide

## 1. Kya hai ye?

`np.histogram()` data ko **bins (buckets)** mein daal ke count karta hai ki har bucket mein kitni values aayi. Ye **sirf numbers calculate karta hai** — koi graph nahi banata. Graph banane ke liye matplotlib chahiye (neeche cover kiya hai).

## 2. Syntax

```python
np.histogram(a, bins=10, range=None)
```

| Parameter | Matlab |
|---|---|
| `a` | Tera data array |
| `bins` | Kitne buckets banane hain (default 10) |
| `range` | `(min, max)` tuple — na do to data ke actual min-max se le lega |

## 3. Working — step by step

**Step 1: Range decide karta hai**
Data ka minimum aur maximum dekhta hai (ya jo `range` mein diya). Ye poora range bins mein divide hoga.

**Step 2: Range ko equal-width bins mein todta hai**
Range `[0, 10]` aur `bins=5` ho to har bin ki width = `(10-0)/5 = 2`.
Bins: `[0,2), [2,4), [4,6), [6,8), [8,10]`

**Step 3: Har data point ko check karta hai kis bin mein fit hota hai**

**Step 4: Us bin ka counter +1 karta hai**

**Step 5: Do arrays return karta hai**
- `hist` → counts array (length = `bins`)
- `bin_edges` → boundaries array (length = `bins + 1`)

## 4. Bin inclusivity rule (important!)

Har bin `[a, b)` hoti hai — **left included, right excluded**.

- `a` (left edge) → agar value bilkul `a` ke barabar hai, is bin mein aayegi
- `b` (right edge) → agar value bilkul `b` ke barabar hai, is bin mein **nahi** aayegi, agle bin mein jaayegi

**Exception:** sirf **last bin** dono taraf inclusive hoti hai `[a, b]` — kyunki uske aage koi bin hi nahi hai.

### Example

```python
import numpy as np

data = [0, 2, 4, 6, 8, 10]
hist, bin_edges = np.histogram(data, bins=5, range=(0, 10))

print(bin_edges)  # [0. 2. 4. 6. 8. 10.]
print(hist)        # [1 1 1 1 2]
```

Bins:
1. `[0, 2)` → sirf `0` → count = 1
2. `[2, 4)` → sirf `2` → count = 1
3. `[4, 6)` → sirf `4` → count = 1
4. `[6, 8)` → sirf `6` → count = 1
5. `[8, 10]` ← **last bin, dono taraf inclusive** → `8` aur `10` dono → count = 2

> **Yaad rakhne ka trick:** Bins ek train ke coaches hain. Har coach ka entry gate front pe hai (left included), exit gate peeche band hai (right excluded) — jo front se ghusega wahi uska passenger. Sirf **last coach ka peeche wala gate bhi khula hai** (train khatam ho rahi hai, koi agla coach nahi).

## 5. Full example

```python
import numpy as np

data = [1, 2, 2, 3, 5, 7, 8, 9]
hist, bin_edges = np.histogram(data, bins=4)

print(hist)        # [3 1 1 3]
print(bin_edges)   # [1. 3. 5. 7. 9.]
```

- `[1,3)` → 1,2,2 → 3
- `[3,5)` → 3 → 1
- `[5,7)` → 5 → 1
- `[7,9]` → 7,8,9 → 3 (last bin, dono inclusive)

## 6. Matplotlib ka istemal karke histogram dikhana

### Method A — Direct (easiest, recommended)

`plt.hist()` internally `np.histogram` jaisa hi logic use karta hai counting ke liye, phir seedha bar chart bana deta hai.

```python
import matplotlib.pyplot as plt

data = [1, 2, 2, 3, 5, 7, 8, 9]

plt.hist(data, bins=4, edgecolor='black')
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.title("Histogram")
plt.show()
```

Bas itna hi — `plt.hist()` khud `np.histogram` wala kaam kar leta hai andar hi andar.

### Method B — Manual (jab tumhe `np.histogram` ke output pe control chahiye)

Kabhi kabhi tumhe pehle `hist` aur `bin_edges` alag se calculate karne hote hain (jaise kisi aur calculation ke liye use karna ho), aur phir sirf plot karna ho. Tab `plt.bar()` use karte hain:

```python
import numpy as np
import matplotlib.pyplot as plt

data = [1, 2, 2, 3, 5, 7, 8, 9]

# Step 1: histogram calculate karo
hist, bin_edges = np.histogram(data, bins=4)

# Step 2: bar chart banao using bin edges
plt.bar(bin_edges[:-1], hist, width=np.diff(bin_edges), edgecolor='black', align='edge')
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.title("Histogram (manual using np.histogram)")
plt.show()
```

**Kyun `bin_edges[:-1]`?** Kyunki `bin_edges` mein `bins+1` values hoti hain (edges), lekin bars sirf `bins` hi honge. Isliye last edge chhod dete hain — har bar apne **left edge** se start hoti hai.

**Kyun `width=np.diff(bin_edges)`?** Taaki har bar ki width uske actual bin-width ke barabar ho (agar bins equal-width nahi hain to ye zaroori hai).

### Kab Method A vs Method B use karein?

| Situation | Method |
|---|---|
| Sirf visualize karna hai | Method A (`plt.hist`) |
| Counts pe aage calculation bhi karni hai (e.g., normalize karna, compare karna) | Method B (`np.histogram` + `plt.bar`) |

## 7. Quick summary

- `np.histogram()` → sirf counting karta hai, koi plot nahi
- Bins `[a, b)` hoti hain, sirf last bin `[a, b]`
- `plt.hist()` → direct plotting, khud counting kar leta hai
- `np.histogram()` + `plt.bar()` → jab counts pe control chahiye ho pehle


In [ ]:
#np.corrcoef returns pearson product moment correlation 

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

In [ ]:
#np.isin function jo hai wo ek saath multiple cheezo ko array main dhundhta hai and jahan to be searched elements mil jaate hai wahan true aata hai else false return a boolean array

items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]


In [39]:
# np.flip() array ka shape preserve karte hue ye specified axis ke along array ko palta dega like flip kr dega seedhe ko ulta ulte ko seedha 
print(a)
print()
np.flip(a)

[35 36 78 27 70 98  2  3 30 45 91 12 52 20 81]



array([81, 20, 52, 12, 91, 45, 30,  3,  2, 98, 70, 27, 78, 36, 35],
      dtype=int32)

In [ ]:
print(b)
print()
print(np.flip(b)) #since axis specified nhi hai both row and column flipping hojayega 
print()
print(np.flip(b,axis=0)) #column wise flip  matlab column jo hai khade main woh palat bjayega 
print()
print(np.flip(b,axis=1))
print()
print(np.flip(np.flip(b,axis=0),axis=1)) #yeh dekho ki  yeh bina axis diye wale ko match khata hai matlab agar axis nhi doge to column wise flip then row wise flip  


[[40 79 79 72]
 [69 64 93 97]
 [92 73  9 76]
 [67 61 93 63]
 [64 12 31  7]
 [35  9  1 36]]

[[36  1  9 35]
 [ 7 31 12 64]
 [63 93 61 67]
 [76  9 73 92]
 [97 93 64 69]
 [72 79 79 40]]

[[35  9  1 36]
 [64 12 31  7]
 [67 61 93 63]
 [92 73  9 76]
 [69 64 93 97]
 [40 79 79 72]]

[[72 79 79 40]
 [97 93 64 69]
 [76  9 73 92]
 [63 93 61 67]
 [ 7 31 12 64]
 [36  1  9 35]]

[[36  1  9 35]
 [ 7 31 12 64]
 [63 93 61 67]
 [76  9 73 92]
 [97 93 64 69]
 [72 79 79 40]]


In [48]:
# np.put() replaces specific elements of an array with given values of p_array.Array indexed works on flateened array 

 #[35 36 78 27 70 98  2  3 30 45 91 12 52 20 81] this is array named a
#  ab suppose mujhe 3 ki jagah 220 laana  hai and 20 ki jagah 169 toh np.put se kaise karunga ?
# Syntax:-np.put(a,jo element replace karne hai unke indexes ko list main daalke likho, jis element se replace karna hai wo element ko list main daalke pass  karo ) 
#list main index and element tabhi pass karna jab multiple elements ho singl eke liye koi zarurat nhi 
#Make permanennt changes to array
np.put(a,[7,13],[220,169]) # ab 2ki jagah 220 and 20 ki jagah 169 aagay hai 
print(a)

np.put(a,7,39)
print(a)

[ 35  36  78  27  70  98   2 220  30  45  91  12  52 169  81]
[ 35  36  78  27  70  98   2  39  30  45  91  12  52 169  81]


In [ ]:
# np.delete
#delete karne ke  liye
#syntax:-np.delete(Array,indextobebedeleted)
#multiple delete karne hai to index to be deleted ki jagah  ek list pass kardo containning indexes of all the elements you want to delete 
np.delete(a,[0,2,4]) #permanent change nhi karta array main array ka ek copy banata hai then us copy se required elements delete karke woh copied array return karta hai 

In [51]:
#Set functions :-
#set ke functions but result numpy array main hi milega  array kke liye hi suse hota hai 

m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

np.intersect1d(m,n)

np.setdiff1d(n,m) #woh saaare elements jo n main ho par m main na ho  
np.setxor1d(m,n) #dono main se ommon walon ko hatake unique rakh legas 
np.in1d(m,1)

AttributeError: module 'numpy' has no attribute 'in1d'