# NumPy Fundamentals — Beginner to Intermediate 
 **🎯 Interview Tip** callout diya gaya hai — un pe extra dhyan dena.

---

## Table of Contents

1. [Part 1: NumPy Basics](#part-1-numpy-basics)
   - [1.1 NumPy kya hai aur kyun zaroori hai](#11-numpy-kya-hai-aur-kyun-zaroori-hai)
   - [1.2 Installation aur Import Convention](#12-installation-aur-import-convention)
   - [1.3 `ndarray` — NumPy ka Core Object](#13-ndarray--numpy-ka-core-object)
   - [1.4 Arrays Banane ke Tareeke](#14-arrays-banane-ke-tareeke)
   - [1.5 Array Attributes](#15-array-attributes)
   - [1.6 Data Types (`dtype`)](#16-data-types-dtype)
2. [Part 2: Array Operations](#part-2-array-operations)
   - [2.1 Indexing aur Slicing](#21-indexing-aur-slicing)
   - [2.2 Boolean aur Fancy Indexing](#22-boolean-aur-fancy-indexing)
   - [2.3 Reshaping Arrays](#23-reshaping-arrays)
   - [2.4 Vectorized Arithmetic Operations](#24-vectorized-arithmetic-operations)
   - [2.5 Broadcasting — Sabse Important Concept](#25-broadcasting--sabse-important-concept)
   - [2.6 Aggregate Functions aur `axis` Parameter](#26-aggregate-functions-aur-axis-parameter)
   - [2.7 Universal Functions (ufuncs)](#27-universal-functions-ufuncs)
3. [Part 3: Intermediate Concepts](#part-3-intermediate-concepts)
   - [3.1 NumPy Itna Fast Kyun Hai](#31-numpy-itna-fast-kyun-hai)
   - [3.2 Copy vs View — Interview Favourite](#32-copy-vs-view--interview-favourite)
   - [3.3 Stacking aur Splitting Arrays](#33-stacking-aur-splitting-arrays)
   - [3.4 `np.random` Module](#34-nprandom-module)
   - [3.5 Linear Algebra Basics](#35-linear-algebra-basics)
   - [3.6 Sorting Arrays](#36-sorting-arrays)
   - [3.7 Common Interview Questions](#37-common-interview-questions)
   - [Quick Recap](#quick-recap)

---

# Part 1: NumPy Basics

## 1.1 NumPy kya hai aur kyun zaroori hai

**NumPy (Numerical Python)** ek library hai jo Python mein **fast, memory-efficient numerical computing** ke liye use hoti hai. Iska core object hai **`ndarray`** (N-dimensional array), jo Python ki built-in `list` se **kaafi zyada fast** hai jab bade numerical data pe kaam karna ho.

**Real life analogy:** Python ka `list` ek **general-purpose bag** hai — usme kuch bhi daal sakte ho (numbers, strings, objects mix karke). NumPy ka `ndarray` ek **specialized, organized tray** hai — sirf **ek hi type** ka data rakhta hai, isliye operations bahut fast ho jaate hain (jaise ek jaisi cheezein sort karna, ek jaisi shape ke boxes stack karna, mixed cheezon se zyada aasaan hai).

```python
import numpy as np

# Python list se numbers add karna — element-wise nahi hota
py_list = [1, 2, 3]
# py_list + 5   ❌ TypeError! list mein directly number nahi jod sakte

# NumPy array se — seedha element-wise operation
np_array = np.array([1, 2, 3])
print(np_array + 5)    # [6 7 8] — har element mein 5 add ho gaya, aasani se!
```

| | Python `list` | NumPy `ndarray` |
|---|---|---|
| **Data types** | Mixed types allowed (`[1, "hi", 3.5]`) | Sirf ek type (`homogeneous`) |
| **Speed** | Slow (bade data pe) | Bahut fast (C mein implemented) |
| **Memory** | Zyada memory leta hai | Kam, compact memory |
| **Operations** | Loop likhna padta hai | Direct vectorized operations (`arr + 5`) |
| **Use case** | General purpose | Numerical/scientific computing, ML, Data Science |

---

## 1.2 Installation aur Import Convention

```bash
pip install numpy
```

```python
import numpy as np    # 'np' ek universal convention hai — har jagah yahi likha jaata hai
```

> **🎯 Interview Tip:** `import numpy as np` likhna sirf convention nahi, **industry standard** hai — koi bhi codebase/interview mein isi tareeke se import expect kiya jaata hai.

---

## 1.3 `ndarray` — NumPy ka Core Object

`ndarray` (N-dimensional array) NumPy ka fundamental data structure hai. "N-dimensional" ka matlab hai ye **1D, 2D, 3D, ya usse zyada dimensions** mein data rakh sakta hai.

```python
# 1D array — ek simple list jaisa
arr_1d = np.array([1, 2, 3])

# 2D array — matrix jaisa (rows aur columns)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 3D array — matrices ka stack
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
```

```mermaid
flowchart TD
    A["1D Array\n[1, 2, 3]"] --> A1["Ek line — jaise ek list"]
    B["2D Array\n[[1,2,3],\n [4,5,6]]"] --> B1["Rows x Columns — jaise\nExcel sheet ya matrix"]
    C["3D Array\n[[[..]], [[..]]]"] --> C1["Matrices ka stack —\njaise images ka batch (RGB channels)"]
```

---

## 1.4 Arrays Banane ke Tareeke

```python
# List se seedha
a = np.array([1, 2, 3])

# Sab zeros ka array
zeros = np.zeros((2, 3))       # 2 rows, 3 columns, sab 0.0
# [[0. 0. 0.]
#  [0. 0. 0.]]

# Sab ones ka array
ones = np.ones((3, 3))

# Kisi specific value se bhara array
full = np.full((2, 2), 7)      # sab 7 se bhara

# range() jaisa, par array return karta hai
arange_arr = np.arange(0, 10, 2)   # [0 2 4 6 8] — start, stop, step

# Equally spaced values — kitne numbers chahiye, ye specify karo
linspace_arr = np.linspace(0, 1, 5)   # [0. 0.25 0.5 0.75 1.] — 0 se 1 tak 5 equal parts mein

# Identity matrix
identity = np.eye(3)    # 3x3 diagonal mein 1, baaki 0

# Random values (Section 3.4 mein detail mein)
random_arr = np.random.rand(2, 2)
```

| Function | Kya deta hai |
|---|---|
| `np.array(list)` | List se array |
| `np.zeros(shape)` | Sab zeros |
| `np.ones(shape)` | Sab ones |
| `np.full(shape, value)` | Sab ek specific value |
| `np.arange(start, stop, step)` | Range jaisa, par array |
| `np.linspace(start, stop, n)` | `n` equally-spaced values |
| `np.eye(n)` | `n x n` identity matrix |

---

## 1.5 Array Attributes

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)      # (2, 3) — 2 rows, 3 columns
print(arr.ndim)        # 2 — kitne dimensions hain
print(arr.size)        # 6 — total elements
print(arr.dtype)       # int64 — data type
print(arr.itemsize)    # 8 — har element kitne bytes leta hai
```

> **🎯 Interview Tip:** `shape`, `ndim`, aur `size` mein confuse mat ho — `shape` **tuple** deta hai (jaise `(2,3)`), `ndim` sirf ek **number** deta hai (dimensions ki count, yaha `2`), `size` **total elements** deta hai (yaha `6` — `2*3`).

---

## 1.6 Data Types (`dtype`)

NumPy arrays **homogeneous** hote hain — sabhi elements ka **ek hi data type** hota hai. Ye hi wajah hai NumPy fast hai (Python list mein har element apna type carry karta hai, extra overhead).

```python
int_arr = np.array([1, 2, 3])
print(int_arr.dtype)    # int64 (ya int32, OS pe depend karta hai)

float_arr = np.array([1.0, 2.5, 3.7])
print(float_arr.dtype)   # float64

# Explicitly type specify karna
explicit_arr = np.array([1, 2, 3], dtype=np.float32)

# Type convert karna (casting)
converted = int_arr.astype(np.float64)
```

```python
# ⚠️ Agar mixed types diye, NumPy sabko ek common type mein convert kar dega (upcasting)
mixed = np.array([1, 2.5, 3])
print(mixed.dtype)    # float64 — int bhi float ban gaye, kyunki ek hi type honi chahiye
```

---

# Part 2: Array Operations

## 2.1 Indexing aur Slicing

```python
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])       # 10 — pehla element
print(arr[-1])      # 50 — aakhri element (negative indexing)
print(arr[1:4])      # [20 30 40] — slicing (index 1 se 3 tak, 4 exclusive)
print(arr[:3])       # [10 20 30] — shuru se index 2 tak
print(arr[::2])      # [10 30 50] — step 2 se (har doosra element)
```

**2D array mein indexing** — `[row, column]` format use hota hai (Python list ki tarah `[row][column]` nahi likhna padta):

```python
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1, 2])      # 6 — row 1, column 2
print(matrix[0])          # [1 2 3] — pura row 0
print(matrix[:, 1])       # [2 5 8] — pura column 1 (saare rows, column index 1)
print(matrix[0:2, 1:3])   # [[2 3], [5 6]] — sub-matrix (rows 0-1, columns 1-2)
```

```mermaid
flowchart LR
    A["matrix[1, 2]"] --> A1["Row 1, Column 2\n= 6"]
    B["matrix[:, 1]"] --> B1["Saare rows,\nColumn 1 = [2, 5, 8]"]
    C["matrix[0]"] --> C1["Pura Row 0\n= [1, 2, 3]"]
```

---

## 2.2 Boolean aur Fancy Indexing

**Boolean Indexing** — condition ke basis pe elements filter karna (bahut common in Data Science):

```python
arr = np.array([10, 25, 30, 45, 50])

mask = arr > 25              # [False False True True True] — Boolean array
print(arr[mask])              # [30 45 50] — sirf True positions ke elements

# Ek line mein
print(arr[arr > 25])          # [30 45 50] — same result, direct

# Modify karna condition ke basis pe
arr[arr > 25] = 0
print(arr)   # [10 25 0 0 0]
```

**Fancy Indexing** — specific indices ki list dekar elements uthana:

```python
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])    # [10 30 50] — index 0, 2, 4 wale elements
```

> **🎯 Interview Tip:** Boolean indexing **Pandas** mein bhi exactly isi tarah kaam karta hai (`df[df['column'] > 5]`) — NumPy ka ye concept samajh lo to Pandas filtering bhi turant clear ho jaayegi.

---

## 2.3 Reshaping Arrays

```python
arr = np.arange(12)     # [0 1 2 3 4 5 6 7 8 9 10 11]

reshaped = arr.reshape(3, 4)    # 3 rows, 4 columns mein convert karo
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# -1 ka matlab "isko khud calculate karo"
auto_reshaped = arr.reshape(3, -1)   # 3 rows, columns khud figure out karo (yahan 4)

flattened = reshaped.flatten()   # wapas 1D mein — [0 1 2 3 4 5 6 7 8 9 10 11]
```

> **⚠️ Important:** `reshape()` ke liye total elements **match** hone chahiye. `arr.reshape(3, 4)` sirf tab chalega jab total elements `12` hon (`3*4=12`). Agar match na ho, `ValueError` aayega.

---

## 2.4 Vectorized Arithmetic Operations

NumPy mein arithmetic operations **element-wise (vectorized)** hote hain — koi loop likhne ki zaroorat nahi:

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)    # [5 7 9]
print(a - b)    # [-3 -3 -3]
print(a * b)    # [4 10 18]   — element-wise multiply, matrix multiplication NAHI
print(a / b)    # [0.25 0.4 0.5]
print(a ** 2)   # [1 4 9]

# Scalar ke saath
print(a * 10)   # [10 20 30] — har element mein 10 multiply
```

> **🎯 Interview Tip:** `a * b` **element-wise** multiplication hai, **matrix multiplication nahi**! Matrix multiplication ke liye `np.dot(a, b)` ya `@` operator use hota hai — ye Section 3.5 mein cover hoga. Ye interview mein bahut common trick question hai.

---

## 2.5 Broadcasting — Sabse Important Concept

**Broadcasting** wo mechanism hai jisse NumPy **different shapes** ke arrays ke beech bhi operations perform kar leta hai, bina explicitly unko same shape banaye.

```python
matrix = np.array([[1, 2, 3], [4, 5, 6]])   # shape (2, 3)
vector = np.array([10, 20, 30])              # shape (3,)

result = matrix + vector
# [[11 22 33]
#  [14 25 36]]
# vector automatically har row mein "broadcast" (repeat) ho gaya
```

```mermaid
flowchart TD
    A["matrix shape: (2, 3)\n[[1,2,3],\n [4,5,6]]"] --> C["Broadcasting"]
    B["vector shape: (3,)\n[10, 20, 30]"] -->|"Automatically\nstretch/repeat hota hai"| B1["[[10,20,30],\n [10,20,30]]"]
    B1 --> C
    C --> D["Result: element-wise add\n[[11,22,33],\n [14,25,36]]"]
```

**Broadcasting Rules** (do shapes compatible hain agar, right se left compare karte hue):
1. Dimensions **equal** hain, YA
2. Inme se ek dimension **1** hai, YA
3. Ek dimension **missing** hai (to treat as 1)

```python
# ✅ Compatible examples
(2, 3) aur (3,)      # → (3,) ko (1,3) treat karke broadcast hota hai
(2, 3) aur (2, 1)     # → column vector har column mein broadcast hota hai
(3, 1) aur (1, 4)      # → dono broadcast hoke (3, 4) result denge

# ❌ Incompatible
(2, 3) aur (4,)        # 3 aur 4 match nahi karte, aur na hi koi 1 hai — ValueError
```

> **🎯 Interview Tip:** Broadcasting NumPy ka **sabse zyada poocha jaane wala concept** hai — samjha do ki ye kaise "chhote array ko bade ke shape mein automatically fit karta hai bina actually memory mein copy banaye" (memory-efficient hai, real copy nahi banta).

---

## 2.6 Aggregate Functions aur `axis` Parameter

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.sum())      # 21 — sab elements ka sum
print(arr.mean())      # 3.5
print(arr.max())       # 6
print(arr.min())       # 1
print(arr.std())       # standard deviation
```

**`axis` parameter** — 2D+ arrays mein specify karta hai **kis direction mein** operation karna hai:

```python
print(arr.sum(axis=0))    # [5 7 9]  — column-wise sum (har column ka sum, top se bottom)
print(arr.sum(axis=1))    # [6 15]    — row-wise sum (har row ka sum, left se right)
```

```mermaid
flowchart TD
    A["arr = [[1,2,3],\n        [4,5,6]]"] --> B["axis=0\n(neeche ki taraf jaate hue,\ncolumns collapse hote hain)"]
    A --> C["axis=1\n(right ki taraf jaate hue,\nrows collapse hote hain)"]
    B --> B1["[5, 7, 9]\n(1+4, 2+5, 3+6)"]
    C --> C1["[6, 15]\n(1+2+3, 4+5+6)"]
```

> **🎯 Interview Tip:** `axis=0` aur `axis=1` mein confuse hona **sabse common mistake** hai. Yaad rakhne ka tareeka: **`axis=0` matlab us direction mein move karo jisme row-index badhta hai (neeche)** — is wajah se columns collapse hoke ek row reh jaati hai. `axis=1` matlab **column-index badhne ki direction (right)** — rows collapse hoke ek column reh jaati hai.

---

## 2.7 Universal Functions (ufuncs)

**ufuncs** wo functions hain jo **element-wise** kaam karte hain, bahut fast (C mein implemented):

```python
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))     # [1. 2. 3. 4.]
print(np.exp(arr))       # e^x har element ka
print(np.log(arr))        # natural log har element ka
print(np.abs(np.array([-1, -2, 3])))   # [1 2 3]
print(np.round(np.array([1.234, 5.678]), 2))   # [1.23 5.68]
```

---

# Part 3: Intermediate Concepts

## 3.1 NumPy Itna Fast Kyun Hai

Ye ek **classic interview question** hai. 3 core reasons:

1. **Contiguous Memory** — NumPy array ke saare elements memory mein **ek saath, lagatar (contiguous block)** mein store hote hain. Python `list` mein elements alag-alag jagah bikhri hui memory mein hote hain (list actually object **pointers** ki list hoti hai).

2. **Homogeneous Data Type** — Sab elements ka same type hone se, CPU ko har element ka type check nahi karna padta — direct raw numbers pe operate karta hai.

3. **Vectorization** — Operations Python-level loop mein nahi, balki optimized **C code** mein internally chalte hain (loop C mein hota hai, Python interpreter overhead nahi lagta).

```mermaid
flowchart LR
    subgraph List["Python list [1,2,3]"]
    L1["Pointer"] -.-> LM1["Object: 1\n(alag memory location)"]
    L2["Pointer"] -.-> LM2["Object: 2\n(alag memory location)"]
    L3["Pointer"] -.-> LM3["Object: 3\n(alag memory location)"]
    end

    subgraph Array["NumPy array [1,2,3]"]
    A1["1 | 2 | 3"] --- A2["Ek hi contiguous\nmemory block"]
    end

    style List fill:#ffcccc
    style Array fill:#ccffcc
```

> **🎯 Interview Tip:** Agar poocha jaaye "NumPy list se fast kyun hai", teeno reasons (contiguous memory, homogeneous type, vectorization/C-level loops) bolna — sirf "fast hai kyunki C mein bana hai" kehna incomplete answer maana jaata hai.

---

## 3.2 Copy vs View — Interview Favourite

Ye topic bahut logon ko confuse karta hai aur interview mein bahut poocha jaata hai.

- **View** — Naya array object banta hai, par **wahi original data (memory)** share karta hai. Ek ko change karoge, doosra bhi change hoga.
- **Copy** — Bilkul **naya, independent** memory mein data ban jaata hai. Ek ko change karne se doosra affect nahi hota.

```python
original = np.array([1, 2, 3, 4, 5])

# Slicing → VIEW deta hai (default behavior NumPy mein)
view = original[1:4]
view[0] = 100
print(original)    # [1 100 3 4 5] — original bhi change ho gaya! (kyunki view same memory hai)

# .copy() → explicit COPY
copy = original.copy()
copy[0] = 999
print(original)    # [1 100 3 4 5] — original change NAHI hua (copy independent hai)
```

```mermaid
flowchart TD
    A["original = [1,2,3,4,5]"] --> B["view = original[1:4]\n(Slicing → VIEW)"]
    A --> C["copy = original.copy()\n(Explicit → COPY)"]
    B -->|"Same memory share karta hai"| B1["view change → original bhi change"]
    C -->|"Independent memory"| C1["copy change → original SAFE"]

    style B1 fill:#fff3cd
    style C1 fill:#ccffcc
```

> **🎯 Interview Tip:** `array.base` check karke pata chal sakta hai koi array View hai ya Copy — agar `.base` `None` return kare, to wo apni khud ki memory ka owner hai (Copy ya original). Agar `.base` kisi doosre array ko point kare, to wo ek View hai. **Basic slicing (`arr[1:4]`) hamesha View deta hai, par Fancy/Boolean indexing (`arr[[0,2]]` ya `arr[arr>2]`) hamesha Copy deta hai** — ye exact distinction interviewers test karte hain.

---

## 3.3 Stacking aur Splitting Arrays

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))     # Vertically stack — [[1 2 3], [4 5 6]]
print(np.hstack((a, b)))     # Horizontally jodo — [1 2 3 4 5 6]
print(np.concatenate((a, b)))  # hstack jaisa hi 1D ke liye — [1 2 3 4 5 6]

arr = np.arange(9)
print(np.split(arr, 3))      # 3 equal parts mein todo — [array([0,1,2]), array([3,4,5]), array([6,7,8])]
```

---

## 3.4 `np.random` Module

```python
np.random.seed(42)              # Reproducibility ke liye — same "random" values har baar milengi

print(np.random.rand(3))         # 3 uniform random values, 0 aur 1 ke beech
print(np.random.randint(1, 10, size=5))   # 5 random integers, 1 se 9 ke beech
print(np.random.randn(3))         # 3 values, normal (Gaussian) distribution se
print(np.random.choice([1, 2, 3, 4], size=2))   # list mein se randomly 2 choose karo
```

> **🎯 Interview Tip:** `np.random.seed(n)` set karna zaroori hota hai jab tumhe **reproducible results** chahiye (jaise ML experiments mein) — bina seed set kiye har run pe different random values aayengi.

---

## 3.5 Linear Algebra Basics

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Matrix multiplication (dot product) — element-wise (*) se DIFFERENT
print(np.dot(a, b))
print(a @ b)          # '@' operator bhi wahi karta hai, modern aur zyada readable

# Transpose
print(a.T)             # rows aur columns swap
# [[1 3]
#  [2 4]]

# Determinant, Inverse (numpy.linalg module se)
from numpy.linalg import det, inv
print(det(a))           # determinant
print(inv(a))            # inverse matrix
```

> **🎯 Interview Tip:** `a * b` (element-wise) aur `a @ b` / `np.dot(a, b)` (matrix multiplication) ka difference bataana bahut common interview question hai — Section 2.4 mein iska warning bhi diya gaya tha, dobara yaad kar lo.

---

## 3.6 Sorting Arrays

```python
arr = np.array([30, 10, 20, 50, 40])

print(np.sort(arr))         # [10 20 30 40 50] — sorted array (naya array, original safe)
print(np.argsort(arr))       # [1 2 0 4 3] — indices jo sorted order dete hain

# 2D array ko axis ke hisaab se sort karna
matrix = np.array([[3, 1], [2, 4]])
print(np.sort(matrix, axis=0))   # column-wise sort
print(np.sort(matrix, axis=1))   # row-wise sort
```

> **🎯 Interview Tip:** `argsort()` bahut useful hai jab tumhe **sorted indices** chahiye, actual sorted values nahi — jaise "top 3 highest marks ke students ka naam batao" jaise problems mein.

---

## 3.7 Common Interview Questions

| Question | Short Answer |
|---|---|
| NumPy array vs Python list? | Homogeneous, contiguous memory, vectorized ops — isliye fast |
| Broadcasting kya hai? | Different shapes ke arrays ke beech operations, bina explicit copy banaye shape match karna |
| `axis=0` vs `axis=1`? | `axis=0` = columns collapse (top-bottom direction), `axis=1` = rows collapse (left-right direction) |
| View vs Copy? | View same memory share karta hai (slicing se milta hai), Copy independent memory hoti hai (`.copy()`, fancy/boolean indexing) |
| `*` vs `np.dot()`/`@`? | `*` element-wise multiply, `dot()`/`@` matrix multiplication |
| `reshape()` kab fail hota hai? | Jab total elements match nahi karte naye shape se |
| NumPy itna fast kyun hai? | Contiguous memory + homogeneous dtype + C-level vectorization |
| `np.nan` kya hai? | "Not a Number" — missing/undefined data represent karne ke liye, float type ka special value |

---

## Quick Recap

```mermaid
%%{init: {'theme': 'dark', 'themeVariables': {'primaryColor': '#3b4252', 'primaryTextColor': '#eceff4', 'primaryBorderColor': '#88c0d0', 'lineColor': '#88c0d0', 'secondaryColor': '#434c5e', 'tertiaryColor': '#4c566a', 'mainBkg': '#2e3440', 'textColor': '#eceff4'}}}%%
mindmap
  root((NumPy\nFundamentals))
    Basics
      ndarray core object
      Creating arrays - zeros ones arange linspace
      shape ndim size dtype
      Homogeneous data types
    Operations
      Indexing and Slicing
      Boolean and Fancy Indexing
      Reshape flatten
      Vectorized arithmetic
      Broadcasting
      axis 0 vs axis 1
      Universal functions
    Intermediate
      Why NumPy is fast
      Copy vs View
      Stack and Split
      np.random
      Linear algebra - dot and transpose
      Sorting - sort and argsort
```

**Bas itna samajh lo:**
- **NumPy** fast hai kyunki homogeneous data + contiguous memory + C-level vectorization
- **Broadcasting** chhote arrays ko bade shape mein "fit" karta hai, bina real copy banaye
- **`axis=0`** columns ko collapse karta hai, **`axis=1`** rows ko collapse karta hai
- **Basic slicing → View** (same memory), **Fancy/Boolean indexing ya `.copy()` → Copy** (independent memory)
- **`*`** element-wise hai, **`@`/`np.dot()`** matrix multiplication hai — ye do alag cheezein hain

---

*Practice ke liye: ek 5x5 random integer matrix banao (`np.random.randint`), phir uska row-wise sum aur column-wise sum nikaalo, sabse bada element ka index (`argmax`) dhoondo, aur last mein matrix ko transpose karke uska determinant nikaalo.*


### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types
____

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [ ]:
#Numpy package bana c main hai par iske around ek wrapper create kara gaya jisse hum isko python  main us ekar skte hai 

In [ ]:
#HOw to create numpy arrays?
import numpy as np
arr=np.array([1,2,3])
print(arr,type(arr))
#1D arrays are aslo called vectors 

In [ ]:
#2D and #3D numpy arrays
import numpy as np
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2,type(arr2))

#3D arrays  are also called tensors in python
arr3=np.array([[[1,2],[3,4]],
               [[5,6],[7,8]]])
print(arr3)

In [ ]:
#Kisis dusre type ka array suppose float
import numpy as np 
arr=np.array([1,2,3],dtype=float)
print(arr,type(arr))

In [ ]:
#arange ke through array creation .
#suppose ek array chahta  hoon jisme 1 to 10 number ho

np.arange(1,11,2) #1 se 11 tak saare elements numpy array main daalde 2 ka jump marke  yni 1,3,5,7,9

In [ ]:
#with reshape we can change shape of numpy arrays 
np.arange(1,11).reshape(5,2) 
#remeber jaise array main jitne element ho unko pehle count karna then reshape ke andar values dena kyunki suppose arrray  main 10 elements hai and 3*3 ke matrix main 9 elements hote hai to ek element kahan jayega matrix hi nhi ban payega error aayega therefore ya  to order 2*5 hoga ya 5*2 kyunki in dono hi matrix main 10 elements aa skte hai 

#array ko change kar dega  5*2 matrix main


In [ ]:
# np.ones() and np.zeroes() se ab arrays create kar skte ho jiske saare element 1 ya 0 honge resppectively 

np.ones((3,3))
np.zeros((3))

In [ ]:
#Agar array ko random number se initialize karna hai kar skte hoo

np.random.random((3))
np.random.random((3,4))
np.random.random((3,3,3))

In [ ]:
#np.linspace(lower_range,upper_range,no of items you want to generate)-Syntax

np.linspace(-10,10,10)
# ye lower range and uppar range ke beech main 10 points nikalega and wo points aise honge ki kinhi bhhi 2 points ke beech space(difference) equal hoga 

# matlab output dekhna and kinhi bhi do point ke beech ka distance nikalna usko koi aur point points ke distance se compare karna .dekhna distance same aayega 

#linspace yhi karta  hai jitne point chahiye honge ek range ke beech us range ki utni equivalence partitioning kar dega 

np.linspace(1,6,5)

In [ ]:
#Identity matrix creation
np.identity(5)

#### Numpy Atttributes 

In [ ]:
#We will use 3 arrays overall to explain each attributes and since numpy is a package /class therefore uske kuch attributes to honge hi jo object access karega
# ndim-Number of dimensions batayega array ka 
import numpy as np
a1=np.arange(1,13)
a2=np.arange(1,10).reshape(3,3)
a3=np.arange(1,9).reshape(2,2,2)
a2.ndim

In [ ]:
#shape batayega har dimension main kitne items hai ?
import numpy as np
a1=np.arange(1,13)
a2=np.arange(1,10).reshape(3,3)
a3=np.arange(1,9).reshape(2,2,2)
a2.shape

a3.shape# (2,2,2) dega yni 3d matrix is represented like (layers,rows,columns ) like pehle2 hai yni 2 layers then rows yni har layer main 2 rows hai and last coloumn yni har layer main 2 rows hai and 2 columns hai 

In [ ]:
import numpy as np
a1=np.arange(1,13)
a2=np.arange(1,10).reshape(3,3)
a3=np.arange(1,9).reshape(2,2,2)

a3.size #no of elements bata dega 


In [ ]:
import numpy as np
a1=np.arange(1,13,dtype=np.int32) #agar sirf 13 likhoge toh 0  se 12 tak 13 items dega 
a2=np.arange(1,10,dtype=float).reshape(3,3)
a3=np.arange(1,9).reshape(2,2,2)

a3.itemsize #a3 ka har item memory main kitna size lega ye batayega(bytes main dega)
a1.itemsize
#32 bit ka int takes 4 bytes and 64 bit ka int takes 8 bytes 

In [ ]:
#dtype datatype batadega 
a1=np.arange(1,13,dtype=np.int32) #agar sirf 13 likhoge toh 0  se 12 tak 13 items dega 
a2=np.arange(1,10,dtype=float).reshape(3,3)
a3=np.arange(1,9).reshape(2,2,2)

a3.dtype

#### Changing Datatype:-

In [ ]:
import numpy as np
a1=np.arange(1,13,dtype=np.int32)
a2=np.arange(1,10,dtype=float).reshape(3,3)
a3=np.arange(1,9).reshape(2,2,2)

print(a3.dtype)
a4=a3.astype(np.int32) #ek naya  array banayega jisme elements to a3 ke honge par unka type jo hoga wo int32 hoga 
print(a4.dtype)


#### Array Operations

In [ ]:
a1=np.arange(1,13).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

#Scalar operations
#arithmetic 
a1*2

# jitne arithmetic operations hai saare kam karenge bruh 

#Relational operations
a2>5 #ab kya  hoga a2 matrix ke har elemetn ko check karega ki kya 5 se bada hai and ek array return kareag jisme true and false usi order main honge jaise elements a2 main the yni jaise 12 is at 0,0 index in a2 when 12>5 hoga to true aayega ye true 0,0 index main jaake store hoga us matrix main jo abhi naya bana hai honge to  hi true aayega else false

In [ ]:
#VEctor arithmetic operations btw matrices 
a1=np.arange(1,13).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
# a1+a2 # since order same hai  to add ho jayega 
a1*a2 #(agar a1 ka order is m*n and a2 ka order is p*q then agar n==p then hi possible else not )

In [ ]:
#Array Functions 
# a1=np.round(np.random.random((3,3))*100) isko aise bhi  likh skta hoon
a1=np.random.random((3,3))
print(a1)
a1=np.round(a1*100)
a1 #hua kya ki random function ne 3,3  ka matrix generate kiya jahan har element 0se 1 ke beech main hain then a1*100 se saare element 0 and 100 ke beech ke aagaye and then round se woh round off hoagye  
 

In [ ]:

import numpy as np
a1=np.round(np.random.random((3,3))*100) 

#max/min/sum prod
print(np.max(a1)) #pure array ka max element dega 
print(np.min(a1))
print(np.prod(a1)) #sare elements ka product kar diya na 
print(np.sum(a1)) #saare elements ka sum nikal  diya 

# ab numpy flexibilityy bhi offer  karta hai .What if har row se max nikalna ho ya min nikalna ho ?
# 0->column represent in axis
# 1->row represent in axis
print(np.min(a1,axis=0)) #har column ka min element ek array mainn daalke array de dega return main

print(np.min(a1,axis=1)) # har row main ka min nikalega array mainn daalega and then  array return kar dega 

print(a1)

In [ ]:
#Statistical operations:
#/mean/median/std/var
import numpy as np
a1=np.round(np.random.random((3,3))*100) 
print(a1)
print(np.mean(a1)) #YE saare elements ka mean de dega par flexibility ka use in chaaro main bhi kar skte ho 
print(np.median(a1)) #Sort karke mid element nikalke de dega 
print(np.var(a1))
print(np.std(a1))

#Trigonometric functions 
np.sin(a1) #har item ka sin calculate karke array main daalke de dega and aaray will be of the order of original matrix 

In [ ]:
#Dot Product 
import numpy as np
a1=np.arange(1,13).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
# (agar a1 ka order is m*n and a2 ka order is p*q then agar n==p then hi possible or not possible at all )

np.dot(a1,a2)

#log and exponents
print(np.log(a1))# a1 ke har element ka log nikLEGA and log ka base will be e

print(np.exp(a1))



In [ ]:
#round/floor/ceil
a2=np.random.random((3,3))*100
print(a2)
print(np.round(a2))
print(np.floor(a2))
print(np.ceil(a2))

In [ ]:
#Indexing and Slicing:-
import numpy as np
a1=np.arange(1,11)
a2=np.arange(12,24).reshape(3,4)
a3=np.arange(1,9).reshape(2,2,2)
print(a1,a2,a3)

#Indexing:-
#Positive/NEgative
print(a1[1]) #similar to python 1D lists

#things get interested fpr 2d array agar koi element access karna hai to pehle yeh batao ki kis row main hi then kis column main suppose you need to find 22 so 22 is in 3rd column 3frd row and 21 is in 2nd column 3rd row  

print(a2[2,2],a2[2,1])

#tensors main bhi pehle layer specify karo then row aaand then column 
print(a3[1,0,0]) #gives 5 

#SLicing se a1 main 2 se 6 tak elements nikalo
print(a1[1:5])

print(a1[2:7:2])

#2D main slicing
#Suppose  1st row nikalni hai 
print(a2[0:1])
#ya to upar  wla syntax ya phir ye neeche wala in dono se rows hi aayenge column  ke liye alag tigdam hai
print(a2[0,:])

#for column
print(a2[:,0]) 
#HOw this syntax works is that comma ke pehle jo kuch hai wo rows ke sath hoga and comma ke baad jo hoga wo hoga column ke saath iska meaning ye hai ki (:) itni rows uthao ab iska matlab hota hai sari rows and fir first column ko uth to isiliye column print ho jataa hai 

In [64]:
#iski flexibility to gajab level ki hai suppose koi bole i want 5and6 adn 9 and 10 through slicing to 
a2=np.arange(12).reshape(3,4)

#sabse pehle hame kitni rows chahiye to rows 2 and 3 yni index 1 onwards and then column hame kitne chahie ?column 2 and 3 yni index 1 and 2 to 
print(a2[1:,1:3])

print(a2[1:,2:])

#ab mujhe chahiye 0 3 8 11 matlab chaaro corner wali value 
print(a2[::2,::3])

# 1 3 9 11
print(a2[::2,1::2])

#4 7
print(a2[1:2,::3])
#1 2 3 
#5 6 7 
print(a2[:2,1:])

[[ 5  6]
 [ 9 10]]
[[ 6  7]
 [10 11]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[[4 7]]
[[1 2 3]
 [5 6 7]]


In [72]:
#Aur khatarnaak 3D array indexing and  slicing 

import numpy as np
a3=np.arange(27).reshape(3,3,3)

print(a3)
#ab suppose is tensor main dusra matrix hai wo chahiye wo to 1st index pe hoga par  lana hai kaise layein?
a3[1]

#pehla and teesra matrix to 
print(a3[::2])

#first wala 2D array yni matrix ka 2nd row print kara ke do that is 3 4 5 
print(a3[0,1,:])

#2nd matrix ka middle column

print(a3[1,:,1])

#22 23 25 26 
print(a3[2,1:,1:])

#Khatarnaak example of 0 2 18 20
print(a3[::2,0,::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


In [81]:
#Iterating:-

# normal iteration bhai for 1D array bhai 

#2d 
a2=np.arange(4).reshape(2,2)
for i in range(len(a2)):
    for j in range(len(a2)):
        print(a2[i,j],end=" ")
    print()  

#3d array  
a3=np.arange(27).reshape(3,3,3)
for i in range(len(a3)):
    for j in range(len(a3)):
        for k in range(len(a3)):
            print(a3[i,j,k],end=" ")
        print()    
    print()  

0 1 
2 3 
0 1 2 
3 4 5 
6 7 8 

9 10 11 
12 13 14 
15 16 17 

18 19 20 
21 22 23 
24 25 26 



In [ ]:
#nditer():- allow you to sequentially access a n dimensioanl array acts as a multiddimensional iterator 
import numpy as np
a3=np.arange(27).reshape(3,3,3)
a5=np.nditer(a3)
for i in a5:
    print(i,end=" ")


0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [ ]:
#Transpose:
import numpy as  np
a2=np.arange(12).reshape(3,4)
#now transpose 2 tareeke se kar skte hai either
print(np.transpose(a2))
#or
print(a2.T)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#np.ravel():-returns a 1D array containing all the element of n dimensional array passed to it as an argument in simple words it converts ndimensional array into a 1-dimensional array
import numpy as  np
a2=np.arange(12).reshape(3,4)
a=np.ravel(a2)
print(a)
#or
for i in np.ravel(a2):
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
#Stacking and Splitting
#Stacking yni 2 ya 2  se zyada arrays ko jodna/stack up  karna 
# Ab stacking 2 tareeke se hogi either horizontal or vertical 

#Horizontal main socho two 2*2 ke matrices hai horizontal stack hue and resulting matrix ka order will be 2*4() horizontal main columns add hogye ya badh gaye)(horizontal staking main rows barabar hona zaruri hai )
import numpy as np 
a4=np.arange(12).reshape(3,4)
a5=np.arange(15).reshape(3,5)

a6=np.hstack((a4,a5))
print(a6)


#VEritical main socho two 2*2 ke matrices hai verticall stack hone ke baad reulting matrix ka order would be 4*2(rows add hogye/no of rows badh  gye )(colums barabar hona zarruri hai )
b=np.arange(16).reshape(4,4)
a7=np.vstack((a4,b))
print(a7)

[[ 0  1  2  3  0  1  2  3  4]
 [ 4  5  6  7  5  6  7  8  9]
 [ 8  9 10 11 10 11 12 13 14]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [17]:
#Splitting:-Opposite of Stacking 
#Can be done in two ways agar aada kaata to vsplit khada kaata to h split 
#Vertical Split Horizontal Spliit(Khada katna)
import numpy as np
a4=np.arange(12).reshape(3,4)
a1,a2=np.hsplit(a4,2)
print(a1,a2)
print(a4)

#VErtical Spliit(aada katna )
a8=np.arange(16).reshape(4,4)
a3,a9,a0=np.vsplit(a4,3)
print(np.vsplit(a8,2))
print(a3,a4,a0)


[[0 1]
 [4 5]
 [8 9]] [[ 2  3]
 [ 6  7]
 [10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[[0 1 2 3]] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[ 8  9 10 11]]
